In [154]:
import boto3
import pandas as pd
from io import BytesIO

In [155]:
s3 = boto3.client(
    "s3",
    endpoint_url="https://51f902078bc0e5d7e38896e8a209ccd2.r2.cloudflarestorage.com",
    aws_access_key_id="309950b4584ab2992107fdbfade53f95",
    aws_secret_access_key="5a5c2db64e3f02b6cb71767d4ce05c3f2262513e5d455977aae6cb5d23359169",
    region_name="auto"
)

BUCKET = "thespine-us-hub"

In [156]:
resp = s3.list_objects_v2(Bucket=BUCKET)

fx_files = [
    obj["Key"]
    for obj in resp.get("Contents", [])
    if "fx" in obj["Key"].lower()
]

fx_files

['fx_price_data.json',
 'fx_sigma_data.json',
 'fx_spreads_data.json',
 'fx_universe.json',
 'spine_us/us_fx_10y_spreads.parquet',
 'spine_us/us_fx_10y_yields.parquet',
 'spine_us/us_fx_ecb_eur_raw.parquet',
 'spine_us/us_fx_fed_raw.parquet',
 'spine_us/us_fx_spot_canonical.parquet',
 'spine_us/us_fx_spot_canonical_t1.parquet',
 'spine_us/us_fx_spot_canonical_t2.parquet',
 'spine_us/us_fx_spot_cross_t2.parquet']

In [150]:
key = "raw/us/wti_inv_stor/df_wti_inv_stor_hist.parquet"

obj = s3.get_object(Bucket=BUCKET, Key=key)

df = pd.read_parquet(BytesIO(obj["Body"].read()))

# print(
# df.head(3), '\n', df.tail(10), '\n', df.columns)
# df.head(), df.tail(), df.columns

In [151]:
# df.head(3)
# df['price'].unique()

In [152]:
df.tail(50)

,Date,INV,WTI_STOR_Sprd_Idx,WTI_INV_Surplus,WTI_INV_Std_Dev_Position,WTI_STOR_Stress_Flag,WTI_Seas_INV_Idx
1294,2024-11-29,423375.0,38.727904,-12569.384615,-0.676326,neutral,1.162158
1295,2024-12-06,421950.0,37.502375,-13953.769231,-0.749857,neutral,1.162720
1296,2024-12-13,421016.0,36.689128,-14871.391026,-0.798652,neutral,1.166981
1297,2024-12-20,416779.0,32.933040,-19087.775641,-1.024018,tight,1.160252
1298,2024-12-27,415601.0,31.907108,-20251.352564,-1.085574,tight,1.167825
1299,2025-01-03,414642.0,31.032278,-21218.967949,-1.138063,tight,1.168182
1300,2025-01-10,412680.0,29.294772,-23173.705128,-1.242314,tight,1.161939
1301,2025-01-17,411663.0,28.451628,-24161.685897,-1.292902,tight,1.154708
1302,2025-01-24,415126.0,31.540289,-20698.576923,-1.107583,tight,1.154937
1303,2025-01-31,423790.0,39.139909,-12120.493590,-0.651605,neutral,1.170692
1304,2025-02-07,427860.0,42.656210,-8155.314103,-0.440627,neutral,1.184334
1305,2025-02-14,432493.0,46.721074,-3627.897436,-0.196736,neutral,1.190996
1306,2025-02-21,430161.0,44.491217,-6067.179487,-0.330527,neutral,1.177681
1307,2025-02-28,433775.0,47.629531,-2595.570513,-0.142228,neutral,1.179020
1308,2025-03-07,435223.0,48.834120,-1271.391026,-0.069953,neutral,1.175594
1309,2025-03-14,436968.0,50.297322,322.525641,0.017839,neutral,1.174593
1310,2025-03-21,433627.0,47.056876,-3170.250000,-0.176587,neutral,1.158896
1311,2025-03-28,439792.0,52.632673,2818.974359,0.157960,neutral,1.166235
1312,2025-04-04,442345.0,54.903892,5239.974359,0.294234,neutral,1.164952
1313,2025-04-11,442860.0,55.238830,5568.262821,0.314330,neutral,1.162583
1314,2025-04-18,443104.0,55.322545,5628.416667,0.319353,neutral,1.156165
1315,2025-04-25,440408.0,52.636296,2774.205128,0.158178,neutral,1.141224
1316,2025-05-02,438376.0,50.620217,651.423077,0.037213,neutral,1.134072
1317,2025-05-09,441830.0,53.791390,3970.743590,0.227483,neutral,1.142463
1318,2025-05-16,443158.0,54.932215,5149.019231,0.295933,neutral,1.148528
1319,2025-05-23,440363.0,52.109708,2189.724359,0.126582,neutral,1.144859
1320,2025-05-30,436059.0,47.833090,-2238.000000,-0.130015,neutral,1.135161
1321,2025-06-06,432415.0,44.197646,-5969.826923,-0.348141,neutral,1.129144
1322,2025-06-13,420942.0,33.011928,-17459.583333,-1.019284,tight,1.103190
1323,2025-06-20,415106.0,27.341689,-23292.634615,-1.359499,tight,1.095044
1324,2025-06-27,418951.0,31.146357,-19416.551282,-1.131219,tight,1.112114
1325,2025-07-04,426021.0,38.021024,-12339.929487,-0.718739,neutral,1.139310
1326,2025-07-11,422162.0,34.323863,-16170.423077,-0.940568,neutral,1.134225
1327,2025-07-18,418993.0,31.293397,-19319.596154,-1.122396,tight,1.130426
1328,2025-07-25,426691.0,38.745894,-11622.480769,-0.675246,neutral,1.157229
1329,2025-08-01,423662.0,35.891494,-14597.967949,-0.846510,neutral,1.152854
1330,2025-08-08,426698.0,38.809626,-11573.147436,-0.671422,neutral,1.165666
1331,2025-08-15,420684.0,33.006888,-17580.814103,-1.019587,tight,1.154684
1332,2025-08-22,418292.0,30.695635,-19972.467949,-1.158262,tight,1.152525
1333,2025-08-29,420707.0,33.103970,-17515.903846,-1.013762,tight,1.167110
1334,2025-09-05,424646.0,36.949965,-13544.935897,-0.783002,neutral,1.183844
1335,2025-09-12,415361.0,28.208293,-22731.134615,-1.307502,tight,1.164639
1336,2025-09-19,414754.0,27.838238,-23236.820513,-1.329706,tight,1.164876
1337,2025-09-26,416546.0,29.706355,-21363.685897,-1.217619,tight,1.167678
1338,2025-10-03,420261.0,33.403336,-17528.038462,-0.995800,neutral,1.168723
1339,2025-10-10,423785.0,36.849099,-13917.038462,-0.789054,neutral,1.173344
1340,2025-10-17,422824.0,36.075640,-14768.288462,-0.835462,neutral,1.162693
1341,2025-10-24,415966.0,29.832083,-21492.544872,-1.210075,tight,1.138831
1342,2025-10-31,421168.0,34.870238,-16164.987179,-0.907786,neutral,1.147060
1343,2025-11-07,427581.0,40.927561,-9702.153846,-0.544346,neutral,1.161624

In [153]:
# df.head(3)
# df['symbol'].unique()
print('this is ~|~ us_fx_10y_spreads', '\n','\n',df['pair'].unique())

KeyError: 'pair'

In [ ]:
# df.head(3)
# df['symbol'].unique()
print('this is ~|~ us_fx_spot_canonical_t1', '\n','\n',df['symbol'].unique())

this is ~|~ us_fx_spot_canonical_t1

 ['EURUSD' 'GBPUSD' 'USDCHF' 'USDCNH' 'USDJPY']

In [ ]:
# df.head(3)
# df['symbol'].unique()
print('this is ~|~ us_fx_spot_canonical_t2', '\n','\n',df['symbol'].unique())

this is ~|~ us_fx_spot_canonical_t2

 ['AUDJPY' 'AUDUSD' 'EURJPY' 'NZDUSD' 'USDCAD' 'USDMXN' 'USDNOK' 'USDSEK'
 'USDZAR']

In [ ]:
# df.head(3)
# df['symbol'].unique()
print('this is ~|~ us_fx_10y_spreads', '\n','\n',df['pair'].unique())

this is ~|~ us_fx_10y_spreads

 ['AUDUSD' 'EURAUD' 'EURCAD' 'EURCHF' 'EURGBP' 'EURNOK' 'EURNZD' 'EURSEK'
 'EURUSD' 'EURZAR' 'GBPUSD' 'NZDAUD' 'NZDUSD' 'USDCAD' 'USDCHF' 'USDJPY'
 'USDNOK' 'USDSEK' 'USDZAR']

# *WTI*

In [ ]:
import os

In [ ]:
import boto3
import pandas as pd
from io import BytesIO

# =========================
# CONFIG
# =========================
BUCKET = "thespine-us-hub"

s3 = boto3.client("s3")

s3 = boto3.client(
    "s3",
    endpoint_url=os.getenv("R2_ENDPOINT"),
    aws_access_key_id=os.getenv("R2_ACCESS_KEY_ID"),
    aws_secret_access_key=os.getenv("R2_SECRET_ACCESS_KEY"),
    region_name=os.getenv("R2_REGION"),
)

# =========================
# LIST WTI / ENERGY FILES
# =========================
resp = s3.list_objects_v2(Bucket=BUCKET)

wti_files = [
    obj["Key"]
    for obj in resp.get("Contents", [])
    if any(x in obj["Key"].lower() for x in ["wti", "crude", "energy"])
]

print("\nWTI / ENERGY FILES:")
for f in wti_files:
    print(f)

WTI / ENERGY FILES:
raw/us/wti_inv_stor/df_wti_inv_stor_hist.parquet
spine_us/leaves/energy/crude_stocks_ex_spr_t2.parquet
spine_us/leaves/energy/wti_price_t1.parquet
spine_us/leaves/wti/wti_leaf.parquet
spine_us/us_wti_index_leaf.parquet

In [ ]:
# =========================
# 1. WTI PRICE (T1)
# =========================
key_price = "spine_us/leaves/energy/wti_price_t1.parquet"

obj_price = s3.get_object(Bucket=BUCKET, Key=key_price)
df_price = pd.read_parquet(BytesIO(obj_price["Body"].read()))

print("\nWTI PRICE (T1) HEAD:")
print(df_price.tail())

print("\nWTI PRICE COLUMNS:")
print(df_price.columns)

WTI PRICE (T1) HEAD:
     symbol       date   close
5025    WTI 2026-03-31  102.86
5026    WTI 2026-04-01  101.90
5027    WTI 2026-04-02  113.23
5028    WTI 2026-04-06  114.01
5029    WTI 2026-04-07  114.58

WTI PRICE COLUMNS:
Index(['symbol', 'date', 'close'], dtype='object')

In [ ]:
# =========================
# 2. INVENTORY (RAW HIST)
# =========================
key_inv_hist = "raw/us/wti_inv_stor/df_wti_inv_stor_hist.parquet"

obj_inv_hist = s3.get_object(Bucket=BUCKET, Key=key_inv_hist)
df_inv_hist = pd.read_parquet(BytesIO(obj_inv_hist["Body"].read()))

print("\nWTI INVENTORY HIST HEAD:")
print(df_inv_hist.head())

print("\nWTI INVENTORY HIST COLUMNS:")
print(df_inv_hist.columns)

WTI INVENTORY HIST HEAD:
        Date       INV  WTI_STOR_Sprd_Idx  WTI_INV_Surplus  \
0 2000-02-11  269796.0                NaN              NaN
1 2000-02-18  269487.0                NaN              NaN
2 2000-02-25  269816.0                NaN              NaN
3 2000-03-03  274502.0                NaN              NaN
4 2000-03-10  274933.0                NaN              NaN

   WTI_INV_Std_Dev_Position WTI_STOR_Stress_Flag  WTI_Seas_INV_Idx
0                       NaN              neutral          0.746806
1                       NaN              neutral          0.742111
2                       NaN              neutral          0.738694
3                       NaN              neutral          0.746109
4                       NaN              neutral          0.742630

WTI INVENTORY HIST COLUMNS:
Index(['Date', 'INV', 'WTI_STOR_Sprd_Idx', 'WTI_INV_Surplus',
       'WTI_INV_Std_Dev_Position', 'WTI_STOR_Stress_Flag', 'WTI_Seas_INV_Idx'],
      dtype='object')

In [ ]:
# =========================
# 3. INVENTORY (T2 CLEAN)
# =========================
key_inv_t2 = "spine_us/leaves/energy/crude_stocks_ex_spr_t2.parquet"

obj_inv_t2 = s3.get_object(Bucket=BUCKET, Key=key_inv_t2)
df_inv_t2 = pd.read_parquet(BytesIO(obj_inv_t2["Body"].read()))

print("\nWTI INVENTORY T2 HEAD:")
print(df_inv_t2.head())

print("\nWTI INVENTORY T2 COLUMNS:")
print(df_inv_t2.columns)

WTI INVENTORY T2 HEAD:
     symbol       date   value
0  WCESTUS1 1982-08-20  338764
1  WCESTUS1 1982-08-27  336138
2  WCESTUS1 1982-09-24  335586
3  WCESTUS1 1982-10-01  334786
4  WCESTUS1 1982-10-08  335260

WTI INVENTORY T2 COLUMNS:
Index(['symbol', 'date', 'value'], dtype='object')

In [ ]:
df_inv_t2.tail()

        symbol       date   value
2266  WCESTUS1 2026-03-06  443103
2267  WCESTUS1 2026-03-13  449259
2268  WCESTUS1 2026-03-20  456185
2269  WCESTUS1 2026-03-27  461636
2270  WCESTUS1 2026-04-03  464717

In [ ]:
key = "us/us_panel/df_spine_us_panel.parquet"

obj = s3.get_object(Bucket=BUCKET, Key=key)
df = pd.read_parquet(BytesIO(obj["Body"].read()))

df["date"] = pd.to_datetime(df["date"])

print(df["date"].max())

KeyError: 'date'

In [ ]:
df.tail(20)

,as_of_date,yld_10y_base,yld_10y_quote,yld_10y_diff,pair,base_ccy,quote_ccy,leaf_group,leaf_name,source_system,updated_at
5937,2026-01-01,3.220984,8.618095,-5.397111,EURZAR,EUR,ZAR,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5938,2026-01-01,4.451000,4.210000,0.241000,GBPUSD,GBP,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5939,2026-01-01,4.510000,4.750000,-0.240000,NZDAUD,NZD,AUD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5940,2026-01-01,4.510000,4.210000,0.300000,NZDUSD,NZD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5941,2026-01-01,4.210000,3.402381,0.807619,USDCAD,USD,CAD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5942,2026-01-01,4.210000,0.270000,3.940000,USDCHF,USD,CHF,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5943,2026-01-01,4.210000,2.240000,1.970000,USDJPY,USD,JPY,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5944,2026-01-01,4.210000,4.122286,0.087714,USDNOK,USD,NOK,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5945,2026-01-01,4.210000,2.800400,1.409600,USDSEK,USD,SEK,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5946,2026-01-01,4.210000,8.618095,-4.408095,USDZAR,USD,ZAR,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5947,2026-02-01,4.770000,4.130000,0.640000,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5948,2026-02-01,4.432400,4.130000,0.302400,GBPUSD,GBP,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5949,2026-02-01,4.450000,4.770000,-0.320000,NZDAUD,NZD,AUD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5950,2026-02-01,4.450000,4.130000,0.320000,NZDUSD,NZD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5951,2026-02-01,4.130000,3.288421,0.841579,USDCAD,USD,CAD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5952,2026-02-01,4.130000,0.250000,3.880000,USDCHF,USD,CHF,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5953,2026-02-01,4.130000,2.110000,2.020000,USDJPY,USD,JPY,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5954,2026-02-01,4.130000,4.162500,-0.032500,USDNOK,USD,NOK,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5955,2026-02-01,4.130000,2.640000,1.490000,USDSEK,USD,SEK,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5956,2026-02-01,4.130000,8.260000,-4.130000,USDZAR,USD,ZAR,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00

In [ ]:
df[df['as_of_date'].isin(df['as_of_date'].unique())].tail(20)

,as_of_date,yld_10y_base,yld_10y_quote,yld_10y_diff,pair,base_ccy,quote_ccy,leaf_group,leaf_name,source_system,updated_at
5937,2026-01-01,3.220984,8.618095,-5.397111,EURZAR,EUR,ZAR,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5938,2026-01-01,4.451000,4.210000,0.241000,GBPUSD,GBP,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5939,2026-01-01,4.510000,4.750000,-0.240000,NZDAUD,NZD,AUD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5940,2026-01-01,4.510000,4.210000,0.300000,NZDUSD,NZD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5941,2026-01-01,4.210000,3.402381,0.807619,USDCAD,USD,CAD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5942,2026-01-01,4.210000,0.270000,3.940000,USDCHF,USD,CHF,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5943,2026-01-01,4.210000,2.240000,1.970000,USDJPY,USD,JPY,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5944,2026-01-01,4.210000,4.122286,0.087714,USDNOK,USD,NOK,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5945,2026-01-01,4.210000,2.800400,1.409600,USDSEK,USD,SEK,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5946,2026-01-01,4.210000,8.618095,-4.408095,USDZAR,USD,ZAR,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5947,2026-02-01,4.770000,4.130000,0.640000,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5948,2026-02-01,4.432400,4.130000,0.302400,GBPUSD,GBP,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5949,2026-02-01,4.450000,4.770000,-0.320000,NZDAUD,NZD,AUD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5950,2026-02-01,4.450000,4.130000,0.320000,NZDUSD,NZD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5951,2026-02-01,4.130000,3.288421,0.841579,USDCAD,USD,CAD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5952,2026-02-01,4.130000,0.250000,3.880000,USDCHF,USD,CHF,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5953,2026-02-01,4.130000,2.110000,2.020000,USDJPY,USD,JPY,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5954,2026-02-01,4.130000,4.162500,-0.032500,USDNOK,USD,NOK,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5955,2026-02-01,4.130000,2.640000,1.490000,USDSEK,USD,SEK,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5956,2026-02-01,4.130000,8.260000,-4.130000,USDZAR,USD,ZAR,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00

In [ ]:
df[df["pair"] == "AUDUSD"].tail(20)
# df.head(20)

,as_of_date,yld_10y_base,yld_10y_quote,yld_10y_diff,pair,base_ccy,quote_ccy,leaf_group,leaf_name,source_system,updated_at
5586,2024-07-01,4.326,4.25,0.076,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5605,2024-08-01,3.976,3.87,0.106,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5624,2024-09-01,3.922,3.72,0.202,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5643,2024-10-01,4.267,4.10,0.167,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5662,2024-11-01,4.544,4.36,0.184,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5681,2024-12-01,4.313,4.39,-0.077,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5700,2025-01-01,4.481,4.63,-0.149,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5719,2025-02-01,4.423,4.45,-0.027,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5738,2025-03-01,4.421,4.28,0.141,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5757,2025-04-01,4.267,4.28,-0.013,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5776,2025-05-01,4.350,4.42,-0.070,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5795,2025-06-01,4.208,4.38,-0.172,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5814,2025-07-01,4.291,4.39,-0.099,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5833,2025-08-01,4.275,4.26,0.015,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5852,2025-09-01,4.298,4.12,0.178,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5871,2025-10-01,4.234,4.06,0.174,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5890,2025-11-01,4.416,4.09,0.326,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5909,2025-12-01,4.719,4.14,0.579,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5928,2026-01-01,4.750,4.21,0.540,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00
5947,2026-02-01,4.770,4.13,0.640,AUDUSD,AUD,USD,fx_stream,fx_10y_spreads,fred_mei,2026-04-08 11:00:34.432118+00:00

In [ ]:
df['yld_10y_diff'].unique()

array([ 0.51789474, -1.4793555 , -0.79296076, ...,  2.02      ,
       -0.0325    , -4.13      ], shape=(5548,))

In [ ]:
import boto3

BUCKET = "thespine-us-hub"

s3 = boto3.client(
    "s3",
    endpoint_url=os.getenv("R2_ENDPOINT"),
    aws_access_key_id=os.getenv("R2_ACCESS_KEY_ID"),
    aws_secret_access_key=os.getenv("R2_SECRET_ACCESS_KEY"),
    region_name=os.getenv("R2_REGION", "auto"),
)

keywords = ["cpi", "inflation", "pce", "breakeven", "fred"]

matches = []
paginator = s3.get_paginator("list_objects_v2")

for page in paginator.paginate(Bucket=BUCKET):
    for obj in page.get("Contents", []):
        key = obj["Key"]
        key_l = key.lower()
        if any(k in key_l for k in keywords):
            matches.append(key)

print(f"matches found: {len(matches)}")
for key in matches:
    print(key)

matches found: 0

In [ ]:
keywords = ["macro", "fred", "us_", "core", "price", "consumer"]

matches = []
paginator = s3.get_paginator("list_objects_v2")

for page in paginator.paginate(Bucket=BUCKET):
    for obj in page.get("Contents", []):
        key = obj["Key"]
        key_l = key.lower()
        if any(k in key_l for k in keywords):
            matches.append(key)

print(f"matches found: {len(matches)}")
for key in matches:
    print(key)

matches found: 32
BeigeBook/sentiment_scores.parquet
fx_price_data.json
spine_us/leaves/energy/wti_price_t1.parquet
spine_us/serving/wti/wti_price_data.json
spine_us/us_equity_index_t1.parquet
spine_us/us_fed_policy_view.parquet
spine_us/us_fed_rate_monitor.parquet
spine_us/us_fx_10y_spreads.parquet
spine_us/us_fx_10y_yields.parquet
spine_us/us_fx_ecb_eur_raw.parquet
spine_us/us_fx_fed_raw.parquet
spine_us/us_fx_spot_canonical.parquet
spine_us/us_fx_spot_canonical_t1.parquet
spine_us/us_fx_spot_canonical_t2.parquet
spine_us/us_fx_spot_cross_t2.parquet
spine_us/us_ir_diff_canonical.parquet
spine_us/us_ir_yields_canonical.parquet
spine_us/us_ism_manu_no_by_industry_canonical.parquet
spine_us/us_ism_manu_pmi_by_industry_canonical.parquet
spine_us/us_ism_manu_pmi_rank_by_industry_canonical.parquet
spine_us/us_ism_manu_pmi_rank_pct_by_industry_canonical.parquet
spine_us/us_ism_nonmanu_no_by_industry_canonical.parquet
spine_us/us_ism_nonmanu_pmi_by_industry_canonical.parquet
spine_us/us_ism_nonmanu_pmi_rank_by_industry_canonical.parquet
spine_us/us_ism_nonmanu_pmi_rank_pct_by_industry_canonical.parquet
spine_us/us_sector_etf_t1.parquet
spine_us/us_spine_core.parquet
spine_us/us_vinv_components.parquet
spine_us/us_vinv_equal_weight.parquet
spine_us/us_wti_index_leaf.parquet
the_Spine/oracle/macro_states/_placeholder
us/us_panel/df_spine_us_panel.parquet

In [178]:
# "raw/us/wti_inv_stor/df_wti_inv_stor_hist.parquet"
# INVENTORY "spine_us/leaves/energy/crude_stocks_ex_spr_t2.parquet"
# PRICES  "spine_us/leaves/energy/wti_price_t1.parquet"
# INVENTORY until  2025-12-24 "spine_us/leaves/wti/wti_leaf.parquet"
# "spine_us/us_wti_index_leaf.parquet"
# "us/us_panel/df_spine_us_panel.parquet"


key_leaf = "spine_us/leaves/energy/crude_stocks_ex_spr_t2.parquet"

obj_leaf = s3.get_object(Bucket=BUCKET, Key=key_leaf)
df_leaf = pd.read_parquet(BytesIO(obj_leaf["Body"].read()))

print("\nWTI LEAF HEAD:")
print(df_leaf.tail())

print("\nWTI LEAF COLUMNS:")
print(df_leaf.columns)

WTI LEAF HEAD:
        symbol       date   value
2266  WCESTUS1 2026-03-06  443103
2267  WCESTUS1 2026-03-13  449259
2268  WCESTUS1 2026-03-20  456185
2269  WCESTUS1 2026-03-27  461636
2270  WCESTUS1 2026-04-03  464717

WTI LEAF COLUMNS:
Index(['symbol', 'date', 'value'], dtype='object')

In [ ]:
# pulls it all the1 way until last reported date in EIA
# spine_us/leaves/energy/crude_stocks_ex_spr_t2.parquet

In [173]:
key = "spine_us/leaves/energy/crude_stocks_ex_spr_t2.parquet"

obj = s3.get_object(Bucket=BUCKET, Key=key)
df = pd.read_parquet(BytesIO(obj["Body"].read()))

print(df.columns)
print(df.tail())

Index(['symbol', 'date', 'value'], dtype='object')
        symbol       date   value
2266  WCESTUS1 2026-03-06  443103
2267  WCESTUS1 2026-03-13  449259
2268  WCESTUS1 2026-03-20  456185
2269  WCESTUS1 2026-03-27  461636
2270  WCESTUS1 2026-04-03  464717

# **FINAL CLEAN**

In [183]:
import boto3

ACCOUNT_ID = "51f902078bc0e5d7e38896e8a209ccd2"
ACCESS_KEY = "309950b4584ab2992107fdbfade53f95"
SECRET_KEY = "5a5c2db64e3f02b6cb71767d4ce05c3f2262513e5d455977aae6cb5d23359169"
BUCKET = "thespine-us-hub"

s3 = boto3.client(
    "s3",
    endpoint_url=f"https://51f902078bc0e5d7e38896e8a209ccd2.r2.cloudflarestorage.com",
    aws_access_key_id=ACCESS_KEY,
    aws_secret_access_key=SECRET_KEY,
    region_name="auto",
)

prefixes = [
    "",
    "serving/",
    "spine_us/",
    "spine_us/leaves/",
    "spine_us/leaves/rates/",
]

for prefix in prefixes:
    print("\n" + "=" * 90)
    print(f"PREFIX: {prefix or '[root]'}")
    resp = s3.list_objects_v2(Bucket=BUCKET, Prefix=prefix)
    for obj in resp.get("Contents", [])[:200]:
        print(obj["Key"])

==========================================================================================
PREFIX: [root]
BeigeBook/beige_topics.parquet
BeigeBook/beige_topics_rbl.parquet
BeigeBook/sentiment_scores.parquet
FedSpeak/combined_policy_leaf.parquet
fx_price_data.json
fx_sigma_data.json
fx_spreads_data.json
fx_universe.json
lab/ft_gmi/ft_gmi_daily.parquet
raw/us/wti_inv_stor/df_wti_inv_stor_hist.parquet
spine_us/leaves/energy/crude_stocks_ex_spr_t2.parquet
spine_us/leaves/energy/wti_price_t1.parquet
spine_us/leaves/rates/rates_spreads_t2.parquet
spine_us/leaves/rates/rates_yields_daily_t1.parquet
spine_us/leaves/rates/rates_yields_monthly_t1.parquet
spine_us/leaves/wti/wti_leaf.parquet
spine_us/serving/wti/wti_inventory_data.json
spine_us/serving/wti/wti_inventory_panel_data.json
spine_us/serving/wti/wti_price_data.json
spine_us/us_equity_index_t1.parquet
spine_us/us_fed_policy_view.parquet
spine_us/us_fed_rate_monitor.parquet
spine_us/us_fx_10y_spreads.parquet
spine_us/us_fx_10y_yields.parquet
spine_us/us_fx_ecb_eur_raw.parquet
spine_us/us_fx_fed_raw.parquet
spine_us/us_fx_spot_canonical.parquet
spine_us/us_fx_spot_canonical_t1.parquet
spine_us/us_fx_spot_canonical_t2.parquet
spine_us/us_fx_spot_cross_t2.parquet
spine_us/us_ir_diff_canonical.parquet
spine_us/us_ir_yields_canonical.parquet
spine_us/us_ism_manu_no_by_industry_canonical.parquet
spine_us/us_ism_manu_pmi_by_industry_canonical.parquet
spine_us/us_ism_manu_pmi_rank_by_industry_canonical.parquet
spine_us/us_ism_manu_pmi_rank_pct_by_industry_canonical.parquet
spine_us/us_ism_nonmanu_no_by_industry_canonical.parquet
spine_us/us_ism_nonmanu_pmi_by_industry_canonical.parquet
spine_us/us_ism_nonmanu_pmi_rank_by_industry_canonical.parquet
spine_us/us_ism_nonmanu_pmi_rank_pct_by_industry_canonical.parquet
spine_us/us_sector_etf_t1.parquet
spine_us/us_spine_core.parquet
spine_us/us_vinv_components.parquet
spine_us/us_vinv_equal_weight.parquet
spine_us/us_wti_index_leaf.parquet
the_Spine/beige_book/_placeholder
the_Spine/beige_book/embeddings/_placeholder
the_Spine/beige_book/parsed_text/_placeholder
the_Spine/beige_book/raw_pdf/_placeholder
the_Spine/daily_panels/_placeholder
the_Spine/fedspeak/_placeholder
the_Spine/fedspeak/drift_signals/_placeholder
the_Spine/fedspeak/embeddings/_placeholder
the_Spine/fedspeak/narratives/_placeholder
the_Spine/fedspeak/transcripts/_placeholder
the_Spine/monthly_panels/_placeholder
the_Spine/oracle/_placeholder
the_Spine/oracle/macro_states/_placeholder
the_Spine/oracle/risk_regimes/_placeholder
the_Spine/oracle/storyboards/_placeholder
the_Spine/raw_data/_placeholder
the_Spine/snapshots/_placeholder
the_Spine/snapshots/glob_us/_placeholder
the_Spine/vinv/1_0/_placeholder
the_Spine/vinv/1_0/benchmarks/_placeholder
the_Spine/vinv/1_0/benchmarks/vinv_benchmarks_monthly.parquet
the_Spine/vinv/1_0/monthly_panels/_placeholder
the_Spine/vinv/1_0/monthly_panels/vinv_monthly_panel.parquet
the_Spine/vinv/1_0/portfolio/_placeholder
the_Spine/vinv/1_0/portfolio/vinv_portfolio_monthly.parquet
the_Spine/vinv/_placeholder
us/us_panel/df_spine_us_panel.parquet

==========================================================================================
PREFIX: serving/

==========================================================================================
PREFIX: spine_us/
spine_us/leaves/energy/crude_stocks_ex_spr_t2.parquet
spine_us/leaves/energy/wti_price_t1.parquet
spine_us/leaves/rates/rates_spreads_t2.parquet
spine_us/leaves/rates/rates_yields_daily_t1.parquet
spine_us/leaves/rates/rates_yields_monthly_t1.parquet
spine_us/leaves/wti/wti_leaf.parquet
spine_us/serving/wti/wti_inventory_data.json
spine_us/serving/wti/wti_inventory_panel_data.json
spine_us/serving/wti/wti_price_data.json
spine_us/us_equity_index_t1.parquet
spine_us/us_fed_policy_view.parquet
spine_us/us_fed_rate_monitor.parquet
spine_us/us_fx_10y_spreads.parquet
spine_us/us_fx_10y_yields.parquet
spine_us/us_fx_ecb_eur_raw.parquet
spine_us/us_fx_fed_raw.parquet
spine_us/us_fx_spot_canonical.parquet
spine_us/us_fx_spot_canonical_t1.parquet
spine_us/us_fx_spot_canonical_t2.parquet
spine_us/us_fx_spot_cross_t2.parquet
spine_us/us_ir_diff_canonical.parquet
spine_us/us_ir_yields_canonical.parquet
spine_us/us_ism_manu_no_by_industry_canonical.parquet
spine_us/us_ism_manu_pmi_by_industry_canonical.parquet
spine_us/us_ism_manu_pmi_rank_by_industry_canonical.parquet
spine_us/us_ism_manu_pmi_rank_pct_by_industry_canonical.parquet
spine_us/us_ism_nonmanu_no_by_industry_canonical.parquet
spine_us/us_ism_nonmanu_pmi_by_industry_canonical.parquet
spine_us/us_ism_nonmanu_pmi_rank_by_industry_canonical.parquet
spine_us/us_ism_nonmanu_pmi_rank_pct_by_industry_canonical.parquet
spine_us/us_sector_etf_t1.parquet
spine_us/us_spine_core.parquet
spine_us/us_vinv_components.parquet
spine_us/us_vinv_equal_weight.parquet
spine_us/us_wti_index_leaf.parquet

==========================================================================================
PREFIX: spine_us/leaves/
spine_us/leaves/energy/crude_stocks_ex_spr_t2.parquet
spine_us/leaves/energy/wti_price_t1.parquet
spine_us/leaves/rates/rates_spreads_t2.parquet
spine_us/leaves/rates/rates_yields_daily_t1.parquet
spine_us/leaves/rates/rates_yields_monthly_t1.parquet
spine_us/leaves/wti/wti_leaf.parquet

==========================================================================================
PREFIX: spine_us/leaves/rates/
spine_us/leaves/rates/rates_spreads_t2.parquet
spine_us/leaves/rates/rates_yields_daily_t1.parquet
spine_us/leaves/rates/rates_yields_monthly_t1.parquet

In [185]:
import boto3
from pathlib import Path

# ACCOUNT_ID = "YOUR_ACCOUNT_ID"
# ACCESS_KEY = "YOUR_R2_ACCESS_KEY_ID"
# SECRET_KEY = "YOUR_R2_SECRET_ACCESS_KEY"
# BUCKET = "thespine-us-hub"

s3 = boto3.client(
    "s3",
    endpoint_url=f"https://51f902078bc0e5d7e38896e8a209ccd2.r2.cloudflarestorage.com",
    aws_access_key_id=ACCESS_KEY,
    aws_secret_access_key=SECRET_KEY,
    region_name="auto",
)

download_dir = Path(r"C:\Users\Rand Sobczak Jr\_rts\3_AI\IsoVector\_py\r2_tmp")
download_dir.mkdir(parents=True, exist_ok=True)

keys = [
    "spine_us/us_fx_10y_spreads.parquet",
    "spine_us/us_ir_diff_canonical.parquet",
    "spine_us/us_equity_index_t1.parquet",
    "spine_us/us_sector_etf_t1.parquet",
    "spine_us/us_ism_manu_pmi_by_industry_canonical.parquet",
    "spine_us/us_ism_nonmanu_pmi_by_industry_canonical.parquet",
]

for key in keys:
    local_path = download_dir / Path(key).name
    try:
        s3.download_file(BUCKET, key, str(local_path))
        print(f"DOWNLOADED: {key} -> {local_path}")
    except Exception as e:
        print(f"FAILED: {key} | {e}")

DOWNLOADED: spine_us/us_fx_10y_spreads.parquet -> C:\Users\Rand Sobczak Jr\_rts\3_AI\IsoVector\_py\r2_tmp\us_fx_10y_spreads.parquet
DOWNLOADED: spine_us/us_ir_diff_canonical.parquet -> C:\Users\Rand Sobczak Jr\_rts\3_AI\IsoVector\_py\r2_tmp\us_ir_diff_canonical.parquet
DOWNLOADED: spine_us/us_equity_index_t1.parquet -> C:\Users\Rand Sobczak Jr\_rts\3_AI\IsoVector\_py\r2_tmp\us_equity_index_t1.parquet
DOWNLOADED: spine_us/us_sector_etf_t1.parquet -> C:\Users\Rand Sobczak Jr\_rts\3_AI\IsoVector\_py\r2_tmp\us_sector_etf_t1.parquet
DOWNLOADED: spine_us/us_ism_manu_pmi_by_industry_canonical.parquet -> C:\Users\Rand Sobczak Jr\_rts\3_AI\IsoVector\_py\r2_tmp\us_ism_manu_pmi_by_industry_canonical.parquet
DOWNLOADED: spine_us/us_ism_nonmanu_pmi_by_industry_canonical.parquet -> C:\Users\Rand Sobczak Jr\_rts\3_AI\IsoVector\_py\r2_tmp\us_ism_nonmanu_pmi_by_industry_canonical.parquet

In [186]:
import pandas as pd
from pathlib import Path

base = Path(r"C:\Users\Rand Sobczak Jr\_rts\3_AI\IsoVector\_py\r2_tmp")

files = {
    "us_fx_10y_spreads": base / "us_fx_10y_spreads.parquet",
    "us_ir_diff_canonical": base / "us_ir_diff_canonical.parquet",
    "us_equity_index_t1": base / "us_equity_index_t1.parquet",
    "us_sector_etf_t1": base / "us_sector_etf_t1.parquet",
    "us_ism_manu_pmi_by_industry_canonical": base / "us_ism_manu_pmi_by_industry_canonical.parquet",
    "us_ism_nonmanu_pmi_by_industry_canonical": base / "us_ism_nonmanu_pmi_by_industry_canonical.parquet",
}

def add_date_column(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    if "date" in df.columns:
        df["date_std"] = pd.to_datetime(df["date"], errors="coerce")
    elif "as_of_date" in df.columns:
        df["date_std"] = pd.to_datetime(df["as_of_date"], errors="coerce")
    elif "Date" in df.columns:
        df["date_std"] = pd.to_datetime(df["Date"], errors="coerce")
    else:
        df["date_std"] = pd.NaT
    return df

for name, path in files.items():
    print("\n" + "=" * 100)
    print(name.upper())
    print("=" * 100)

    df = pd.read_parquet(path)
    df = add_date_column(df)

    print("\nCOLUMNS:")
    print(df.columns.tolist())

    print("\nSHAPE:")
    print(df.shape)

    if "date_std" in df.columns and df["date_std"].notna().any():
        print("\nDATE RANGE:")
        print(df["date_std"].min(), "->", df["date_std"].max())

    likely_id_cols = [c for c in ["pair", "symbol", "base_ccy", "quote_ccy", "leaf_name", "industry", "sector"] if c in df.columns]
    if likely_id_cols:
        print("\nID COLUMNS:")
        for c in likely_id_cols:
            vals = df[c].dropna().astype(str).unique()[:10]
            print(f"{c}: {list(vals)}")

    print("\nTAIL:")
    print(df.tail())

====================================================================================================
US_FX_10Y_SPREADS
====================================================================================================

COLUMNS:
['as_of_date', 'yld_10y_base', 'yld_10y_quote', 'yld_10y_diff', 'pair', 'base_ccy', 'quote_ccy', 'leaf_group', 'leaf_name', 'source_system', 'updated_at', 'date_std']

SHAPE:
(5957, 12)

DATE RANGE:
2000-01-01 00:00:00 -> 2026-02-01 00:00:00

ID COLUMNS:
pair: ['AUDUSD', 'EURAUD', 'EURCAD', 'EURCHF', 'EURGBP', 'EURNOK', 'EURNZD', 'EURSEK', 'EURUSD', 'EURZAR']
base_ccy: ['AUD', 'EUR', 'GBP', 'NZD', 'USD']
quote_ccy: ['USD', 'AUD', 'CAD', 'CHF', 'GBP', 'NOK', 'NZD', 'SEK', 'ZAR', 'JPY']
leaf_name: ['fx_10y_spreads']

TAIL:
     as_of_date  yld_10y_base  yld_10y_quote  yld_10y_diff    pair base_ccy  \
5952 2026-02-01          4.13         0.2500        3.8800  USDCHF      USD
5953 2026-02-01          4.13         2.1100        2.0200  USDJPY      USD
5954 2026-02-01          4.13         4.1625       -0.0325  USDNOK      USD
5955 2026-02-01          4.13         2.6400        1.4900  USDSEK      USD
5956 2026-02-01          4.13         8.2600       -4.1300  USDZAR      USD

     quote_ccy leaf_group       leaf_name source_system  \
5952       CHF  fx_stream  fx_10y_spreads      fred_mei
5953       JPY  fx_stream  fx_10y_spreads      fred_mei
5954       NOK  fx_stream  fx_10y_spreads      fred_mei
5955       SEK  fx_stream  fx_10y_spreads      fred_mei
5956       ZAR  fx_stream  fx_10y_spreads      fred_mei

                           updated_at   date_std
5952 2026-04-14 11:06:25.856720+00:00 2026-02-01
5953 2026-04-14 11:06:25.856720+00:00 2026-02-01
5954 2026-04-14 11:06:25.856720+00:00 2026-02-01
5955 2026-04-14 11:06:25.856720+00:00 2026-02-01
5956 2026-04-14 11:06:25.856720+00:00 2026-02-01

====================================================================================================
US_IR_DIFF_CANONICAL
====================================================================================================

COLUMNS:
['as_of_date', 'pair', 'base_ccy', 'quote_ccy', 'base_10y_yield', 'quote_10y_yield', 'diff_10y_bp', 'leaf_group', 'leaf_name', 'source_system', 'updated_at', 'date_std']

SHAPE:
(6842, 12)

DATE RANGE:
2000-01-01 00:00:00 -> 2025-11-01 00:00:00

ID COLUMNS:
pair: ['AUDCAD', 'AUDJPY', 'AUDUSD', 'EURAUD', 'EURCAD', 'EURCHF', 'EURGBP', 'EURJPY', 'EURNOK', 'EURNZD']
base_ccy: ['AUD', 'EUR', 'GBP', 'NZD', 'USD']
quote_ccy: ['CAD', 'JPY', 'USD', 'AUD', 'CHF', 'GBP', 'NOK', 'NZD', 'SEK', 'ZAR']
leaf_name: ['IR_DIFF_CANONICAL']

TAIL:
     as_of_date    pair base_ccy quote_ccy  base_10y_yield  quote_10y_yield  \
6837 2025-11-01  USDCHF      USD       CHF            4.09           0.1900
6838 2025-11-01  USDJPY      USD       JPY            4.09           1.8050
6839 2025-11-01  USDNOK      USD       NOK            4.09           4.0223
6840 2025-11-01  USDSEK      USD       SEK            4.09           2.6579
6841 2025-11-01  USDZAR      USD       ZAR            4.09           9.1245

      diff_10y_bp leaf_group          leaf_name            source_system  \
6837       390.00         IR  IR_DIFF_CANONICAL  PUBLIC_CENTRAL_BANK_API
6838       228.50         IR  IR_DIFF_CANONICAL  PUBLIC_CENTRAL_BANK_API
6839         6.77         IR  IR_DIFF_CANONICAL  PUBLIC_CENTRAL_BANK_API
6840       143.21         IR  IR_DIFF_CANONICAL  PUBLIC_CENTRAL_BANK_API
6841      -503.45         IR  IR_DIFF_CANONICAL  PUBLIC_CENTRAL_BANK_API

                    updated_at   date_std
6837 2026-04-14 00:00:00+00:00 2025-11-01
6838 2026-04-14 00:00:00+00:00 2025-11-01
6839 2026-04-14 00:00:00+00:00 2025-11-01
6840 2026-04-14 00:00:00+00:00 2025-11-01
6841 2026-04-14 00:00:00+00:00 2025-11-01

====================================================================================================
US_EQUITY_INDEX_T1
====================================================================================================

COLUMNS:
['symbol', 'date', 'open', 'high', 'low', 'close', 'volume', 'source', 'date_std']

SHAPE:
(38529, 9)

DATE RANGE:
2000-01-03 00:00:00 -> 2026-04-13 00:00:00

ID COLUMNS:
symbol: ['DIA', 'ITOT', 'IWM', 'MDY', 'QQQ', 'SPY']

TAIL:
      symbol       date    open    high     low   close    volume  source  \
38524    SPY 2026-04-07  656.65  659.61  651.06  659.22  69980362  tiingo
38525    SPY 2026-04-08  676.39  677.08  671.46  676.01  93606114  tiingo
38526    SPY 2026-04-09  674.84  681.16  673.77  679.91  57134445  tiingo
38527    SPY 2026-04-10  681.32  682.03  678.45  679.46  42253456  tiingo
38528    SPY 2026-04-13  677.41  686.30  676.58  686.10  52151045  tiingo

        date_std
38524 2026-04-07
38525 2026-04-08
38526 2026-04-09
38527 2026-04-10
38528 2026-04-13

====================================================================================================
US_SECTOR_ETF_T1
====================================================================================================

COLUMNS:
['symbol', 'date', 'open', 'high', 'low', 'close', 'volume', 'source', 'date_std']

SHAPE:
(64078, 9)

DATE RANGE:
2000-01-03 00:00:00 -> 2026-04-13 00:00:00

ID COLUMNS:
symbol: ['XLB', 'XLC', 'XLE', 'XLF', 'XLI', 'XLK', 'XLP', 'XLRE', 'XLU', 'XLV']

TAIL:
      symbol       date    open     high      low   close    volume  source  \
64073    XLY 2026-04-07  108.11  108.180  106.450  107.77   8956357  tiingo
64074    XLY 2026-04-08  112.25  112.610  110.275  110.82  14442412  tiingo
64075    XLY 2026-04-09  110.82  112.890  110.395  112.74   6660503  tiingo
64076    XLY 2026-04-10  113.00  113.460  112.240  112.89   5607449  tiingo
64077    XLY 2026-04-13  112.34  113.945  112.000  113.92   5939357  tiingo

        date_std
64073 2026-04-07
64074 2026-04-08
64075 2026-04-09
64076 2026-04-10
64077 2026-04-13

====================================================================================================
US_ISM_MANU_PMI_BY_INDUSTRY_CANONICAL
====================================================================================================

COLUMNS:
['as_of_date', 'country', 'ccy', 'sector_name', 'pmi_value', 'leaf_group', 'leaf_name', 'source_system', 'updated_at', 'date_std']

SHAPE:
(1260, 10)

DATE RANGE:
2020-01-01 00:00:00 -> 2025-10-01 00:00:00

ID COLUMNS:
leaf_name: ['us_ism_manu_pmi_by_industry_canonical']

TAIL:
     as_of_date country  ccy                                sector_name  \
1255 2025-10-01      US  USD                         Primary Metals_pmi
1256 2025-10-01      US  USD  Printing & Related Support Activities_pmi
1257 2025-10-01      US  USD                          Textile Mills_pmi
1258 2025-10-01      US  USD               Transportation Equipment_pmi
1259 2025-10-01      US  USD                          Wood Products_pmi

      pmi_value leaf_group                              leaf_name  \
1255          6  MACRO_ISM  us_ism_manu_pmi_by_industry_canonical
1256         -8  MACRO_ISM  us_ism_manu_pmi_by_industry_canonical
1257        -12  MACRO_ISM  us_ism_manu_pmi_by_industry_canonical
1258          4  MACRO_ISM  us_ism_manu_pmi_by_industry_canonical
1259         -7  MACRO_ISM  us_ism_manu_pmi_by_industry_canonical

       source_system                       updated_at   date_std
1255  ISM_MANU_EXCEL 2025-11-24 22:13:53.881753+00:00 2025-10-01
1256  ISM_MANU_EXCEL 2025-11-24 22:13:53.881753+00:00 2025-10-01
1257  ISM_MANU_EXCEL 2025-11-24 22:13:53.881753+00:00 2025-10-01
1258  ISM_MANU_EXCEL 2025-11-24 22:13:53.881753+00:00 2025-10-01
1259  ISM_MANU_EXCEL 2025-11-24 22:13:53.881753+00:00 2025-10-01

====================================================================================================
US_ISM_NONMANU_PMI_BY_INDUSTRY_CANONICAL
====================================================================================================

COLUMNS:
['as_of_date', 'country', 'ccy', 'sector_name', 'pmi_value', 'leaf_group', 'leaf_name', 'source_system', 'updated_at', 'date_std']

SHAPE:
(1260, 10)

DATE RANGE:
2020-01-01 00:00:00 -> 2025-10-01 00:00:00

ID COLUMNS:
leaf_name: ['us_ism_nonmanu_pmi_by_industry_canonical']

TAIL:
     as_of_date country  ccy                        sector_name  pmi_value  \
1255 2025-10-01      US  USD  Real Estate, Rental & Leasing_pmi          8
1256 2025-10-01      US  USD                   Retail Trade_pmi         10
1257 2025-10-01      US  USD   Transportation & Warehousing_pmi          5
1258 2025-10-01      US  USD                      Utilities_pmi          6
1259 2025-10-01      US  USD                Wholesale Trade_pmi          9

     leaf_group                                 leaf_name      source_system  \
1255  MACRO_ISM  us_ism_nonmanu_pmi_by_industry_canonical  ISM_NONMANU_EXCEL
1256  MACRO_ISM  us_ism_nonmanu_pmi_by_industry_canonical  ISM_NONMANU_EXCEL
1257  MACRO_ISM  us_ism_nonmanu_pmi_by_industry_canonical  ISM_NONMANU_EXCEL
1258  MACRO_ISM  us_ism_nonmanu_pmi_by_industry_canonical  ISM_NONMANU_EXCEL
1259  MACRO_ISM  us_ism_nonmanu_pmi_by_industry_canonical  ISM_NONMANU_EXCEL

                           updated_at   date_std
1255 2025-11-24 22:55:55.180780+00:00 2025-10-01
1256 2025-11-24 22:55:55.180780+00:00 2025-10-01
1257 2025-11-24 22:55:55.180780+00:00 2025-10-01
1258 2025-11-24 22:55:55.180780+00:00 2025-10-01
1259 2025-11-24 22:55:55.180780+00:00 2025-10-01

In [187]:
import pandas as pd

path = r"C:\Users\Rand Sobczak Jr\_rts\3_AI\IsoVector\_py\r2_tmp\us_fx_10y_spreads.parquet"

df = pd.read_parquet(path)

print(df.tail())
print("\nColumns:")
print(df.columns.tolist())
print("\nMax date:")
print(df["as_of_date"].max())

     as_of_date  yld_10y_base  yld_10y_quote  yld_10y_diff    pair base_ccy  \
5952 2026-02-01          4.13         0.2500        3.8800  USDCHF      USD
5953 2026-02-01          4.13         2.1100        2.0200  USDJPY      USD
5954 2026-02-01          4.13         4.1625       -0.0325  USDNOK      USD
5955 2026-02-01          4.13         2.6400        1.4900  USDSEK      USD
5956 2026-02-01          4.13         8.2600       -4.1300  USDZAR      USD

     quote_ccy leaf_group       leaf_name source_system  \
5952       CHF  fx_stream  fx_10y_spreads      fred_mei
5953       JPY  fx_stream  fx_10y_spreads      fred_mei
5954       NOK  fx_stream  fx_10y_spreads      fred_mei
5955       SEK  fx_stream  fx_10y_spreads      fred_mei
5956       ZAR  fx_stream  fx_10y_spreads      fred_mei

                           updated_at
5952 2026-04-14 11:06:25.856720+00:00
5953 2026-04-14 11:06:25.856720+00:00
5954 2026-04-14 11:06:25.856720+00:00
5955 2026-04-14 11:06:25.856720+00:00
5956 2026-04-14 11:06:25.856720+00:00

Columns:
['as_of_date', 'yld_10y_base', 'yld_10y_quote', 'yld_10y_diff', 'pair', 'base_ccy', 'quote_ccy', 'leaf_group', 'leaf_name', 'source_system', 'updated_at']

Max date:
2026-02-01 00:00:00